---
- name: add ppa
  apt_repository:
    repo: "ppa:chris-lea/redis-server"
    update_cache: yes
    state: present
  become: yes
  become_user: root

- name: install redis
  apt:
    name: redis-server
    state: present
  become: yes
  become_user: root
